# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories: 
      - "/docker/*" 
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
    ignore:
      - dependency-name: "checkmk/check-mk-cloud"
        versions:
          - "2.4.0-x.x.x"
          - "2.5.0-x.x.x"
  - package-ecosystem: "docker"
    directories: 
      - "/docker/*" 
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
