services:
  rtl:
    container_name: RTL
    image: shahanafarooqui/rtl:v0.15.8
    restart: unless-stopped
    volumes:
      - rtl_data:/config
      - rtl_data:/RTL/database
    #ports:
    #  - "3000:3000"
    environment:
      PORT: 3000
      RTL_CONFIG_PATH: /config
      CHANNEL_BACKUP_PATH: /config/lnd/backup
    networks:
      - frontend

volumes:
  rtl_data:
    name: rtl_data

networks:
  frontend:
    external: true