services:
  checkmk:
    image: checkmk/check-mk-raw:2.4.0p16
    container_name: checkmk
    ports:
      - "8000:8000"
      - "5000:5000"
      - "162:162/udp"
    environment:
      - TZ=America/Chicago
      - CMK_PASSWORD=${CMK_PASSWORD:?no password set}
      - CMK_SITE_ID=${CMK_SITE_ID:-cmk}
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - checkmk_data:/omd/sites:rw
    restart: unless-stopped

volumes:
  checkmk_data:
    driver: local
