services:
  pulse:
    container_name: pulse
    image: rcourtman/pulse:4.35.0
    restart: unless-stopped
    volumes:
      - pulse_data:/data
    ports:
      - 7655:7655

volumes:
  pulse_data:
    name: pulse_data