services:
  pulse:
    container_name: pulse
    image: rcourtman/pulse:4.36.2
    restart: unless-stopped
    volumes:
      - pulse_data:/data
    #ports:
    #  - 7655:7655
    networks:
      - frontend

volumes:
  pulse_data:
    name: pulse_data

networks:
  frontend:
    external: true