x-default-container: &default-container
  restart: unless-stopped
  networks:
    - frontend

services: 
  prowlarr: 
    <<: *default-container
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr 
    hostname: prowlarr 
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Chicago
    volumes: 
      - prowlarr_data:/config 
    #ports: 
    #  - 9696:9696 
    depends_on: 
      - flaresolverr 
  flaresolverr: 
    <<: *default-container
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr 
    hostname: flaresolverr 
    environment: 
      - TZ=America/Chicago
      - LOG_LEVEL=${LOG_LEVEL:-info} 
      - LOG_HTML=${LOG_HTML:-false} 
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
  radarr: 
    <<: *default-container
    image: lscr.io/linuxserver/radarr:6.0.4 
    container_name: radarr 
    hostname: radarr 
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Chicago
    volumes: 
      - media_share:/mnt/media 
      - radarr_data:/config
    #ports: 
    #  - 7878:7878 
    depends_on: 
      - prowlarr 
      - deluge 
  sonarr: 
    <<: *default-container
    image: lscr.io/linuxserver/sonarr:4.0.16 
    container_name: sonarr 
    hostname: sonarr
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Chicago
    volumes: 
      - media_share:/mnt/media
      - sonarr_data:/config 
    depends_on: 
      - prowlarr 
      - deluge
    #ports: 
    #  - 8989:8989
  deluge:
    <<: *default-container
    image: lscr.io/linuxserver/deluge:2.2.0
    container_name: deluge
    hostname: deluge
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Chicago
      - DELUGE_LOGLEVEL=info
    volumes:
      - media_share:/mnt/media
      - deluge_data:/config
    ports:
    #  - 8112:8112
      - 62835:62835
      - 62835:62835/udp
      - 58846:58846
  tautulli:
    <<: *default-container
    image: ghcr.io/tautulli/tautulli:v2.16.0
    container_name: tautulli
    volumes:
      - tautulli_data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    #ports:
    #  - 8181:8181
  ombi:
    <<: *default-container
    image: ghcr.io/linuxserver/ombi:development
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ombi_data:/config
    #ports:
    #  - 3579:3579
  audiobookshelf:
    <<: *default-container
    image: ghcr.io/advplyr/audiobookshelf:2.32.1
    container_name: audiobookshelf
    volumes:
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
      - media_share:/mnt/media
    environment:
      - TZ=America/Chicago
    #ports:
    #  - 13378:80
  shelfmark:
    <<: *default-container
    image: ghcr.io/calibrain/shelfmark:1.0.3
    container_name: shelfmark
    environment:
      PUID: 1000
      PGID: 1000
    #ports:
    #  - 8084:8084
    volumes:
      - media_share:/mnt/media
      - shelfmark_config:/config
  # recommendarr:
  #   <<: *default-container
  #   image: tannermiddleton/recommendarr:v1.4.4
  #   container_name: recommendarr
  #   volumes:
  #     - recommendarr_data:/app/server/data
  #   environment:
  #     - NODE_ENV=production
  #     - DOCKER_ENV=false 
  #     - PORT=${PORT:-3000}
  #     - FORCE_SECURE_COOKIES=true
  #     - PUBLIC_URL=${RECOMMENDARR_PUBLIC_URL:-http://localhost:${PORT:-3000}}
  #   #ports:
  #   #  - "${PORT:-3000}:${PORT:-3000}"
  # agregarr:
  #   <<: *default-container
  #   image: agregarr/agregarr:v2.2.1
  #   container_name: agregarr
  #   volumes:
  #     - agregarr_data:/app/config
  #     - media_share:/mnt/media
  #   environment:
  #     - TZ=America/Chicago
  #   #ports:
  #   #  - 7171:7171

networks:
  frontend:
    external: true

volumes:
  prowlarr_data:
    name: prowlarr_data
    external: true
  radarr_data:
    name: radarr_data
  sonarr_data:
    name: sonarr_data
  deluge_data:
    name: deluge_data
  tautulli_data:
    name: tautulli_data
    external: true
  ombi_data:
    name: ombi_data
    external: true
  audiobookshelf_config:
    name: audiobookshelf_config
  audiobookshelf_metadata:
    name: audiobookshelf_metadata
  shelfmark_config:
    name: shelfmark_config
  # recommendarr_data:
  #   name: recommendarr_data
  # agregarr_data:
  #   name: agregarr_data
  media_share:
    name: media_share
    driver: local
    driver_opts:
      type: cifs
      device: ${SMB_SHARE_PATH}
      o: username=${SMB_USER},password=${SMB_PASS},domain=${SMB_DOMAIN},iocharset=utf8,uid=1000,gid=1000