x-default-container: &default-container
  restart: unless-stopped
  networks:
    - frontend

services: 
  prowlarr: 
    <<: *default-container
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr 
    hostname: prowlarr 
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Chicago
    volumes: 
      - prowlarr_data:/config 
    #ports: 
    #  - 9696:9696 
    depends_on: 
      - flaresolverr 
  flaresolverr: 
    <<: *default-container
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr 
    hostname: flaresolverr 
    environment: 
      - TZ=America/Chicago
      - LOG_LEVEL=${LOG_LEVEL:-info} 
      - LOG_HTML=${LOG_HTML:-false} 
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
  radarr: 
    <<: *default-container
    image: lscr.io/linuxserver/radarr:6.0.4 
    container_name: radarr 
    hostname: radarr 
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Chicago
    volumes: 
      - media_share:/mnt/media 
      - radarr_data:/config
    #ports: 
    #  - 7878:7878 
    depends_on: 
      - prowlarr 
      - deluge 
  sonarr: 
    <<: *default-container
    image: lscr.io/linuxserver/sonarr:4.0.16 
    container_name: sonarr 
    hostname: sonarr
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Chicago
    volumes: 
      - media_share:/mnt/media
      - sonarr_data:/config 
    depends_on: 
      - prowlarr 
      - deluge
    #ports: 
    #  - 8989:8989
  deluge:
    <<: *default-container
    image: lscr.io/linuxserver/deluge:2.2.0
    container_name: deluge
    hostname: deluge
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Chicago
      - DELUGE_LOGLEVEL=info
    volumes:
      - media_share:/mnt/media
      - deluge_data:/config
    ports:
    #  - 8112:8112
      - 62835:62835
      - 62835:62835/udp
      - 58846:58846
  tautulli:
    <<: *default-container
    image: ghcr.io/tautulli/tautulli:v2.16.0
    container_name: tautulli
    volumes:
      - tautulli_data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    #ports:
    #  - 8181:8181
  ombi:
    <<: *default-container
    image: ghcr.io/linuxserver/ombi:development
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ombi_data:/config
    #ports:
    #  - 3579:3579
  audiobookshelf:
    <<: *default-container
    image: ghcr.io/advplyr/audiobookshelf:2.32.1
    container_name: audiobookshelf
    volumes:
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
      - media_share:/mnt/media
    environment:
      - TZ=America/Chicago
    #ports:
    #  - 13378:80
  shelfmark:
    <<: *default-container
    image: ghcr.io/calibrain/shelfmark:1.1.1
    container_name: shelfmark
    environment:
      PUID: 1000
      PGID: 1000
    #ports:
    #  - 8084:8084
    volumes:
      - media_share:/mnt/media
      - shelfmark_config:/config
  # recommendarr:
  #   <<: *default-container
  #   image: tannermiddleton/recommendarr:v1.4.4
  #   container_name: recommendarr
  #   volumes:
  #     - recommendarr_data:/app/server/data
  #   environment:
  #     - NODE_ENV=production
  #     - DOCKER_ENV=false 
  #     - PORT=${PORT:-3000}
  #     - FORCE_SECURE_COOKIES=true
  #     - PUBLIC_URL=${RECOMMENDARR_PUBLIC_URL:-http://localhost:${PORT:-3000}}
  #   #ports:
  #   #  - "${PORT:-3000}:${PORT:-3000}"
  # agregarr:
  #   <<: *default-container
  #   image: agregarr/agregarr:v2.2.1
  #   container_name: agregarr
  #   volumes:
  #     - agregarr_data:/app/config
  #     - media_share:/mnt/media
  #   environment:
  #     - TZ=America/Chicago
  #   #ports:
  #   #  - 7171:7171
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v2.5.6
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - media_share:/mnt/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Chicago
      - DB_HOSTNAME=immich-database
      - DB_USERNAME=postgres
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich-redis
      - IMMICH_MEDIA_LOCATION=/mnt/media/immich
    #ports:
    #  - '2283:2283'
    depends_on:
      - immich-redis
      - immich-database
    restart: always
    healthcheck:
      disable: false
    networks:
      - frontend
      - backend
  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - immich_model_cache:/cache
    restart: always
    healthcheck:
      disable: false
    networks:
      - backend
  immich-redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - backend
  immich-database:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - immich_db_data:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  prowlarr_data:
    name: prowlarr_data
    external: true
  radarr_data:
    name: radarr_data
  sonarr_data:
    name: sonarr_data
  deluge_data:
    name: deluge_data
  tautulli_data:
    name: tautulli_data
    external: true
  ombi_data:
    name: ombi_data
    external: true
  audiobookshelf_config:
    name: audiobookshelf_config
  audiobookshelf_metadata:
    name: audiobookshelf_metadata
  shelfmark_config:
    name: shelfmark_config
  # recommendarr_data:
  #   name: recommendarr_data
  # agregarr_data:
  #   name: agregarr_data
  immich_db_data:
    name: immich_db_data
  immich_model_cache:
    name: immich_model_cache
  media_share:
    name: media_share
    driver: local
    driver_opts:
      type: cifs
      device: ${SMB_SHARE_PATH}
      o: username=${SMB_USER},password=${SMB_PASS},domain=${SMB_DOMAIN},iocharset=utf8,uid=1000,gid=1000